### PR TITLE
updated react dependency to 0.14.3_1

### PR DESCRIPTION
**Pull request by marbemac**

### CODE REVIEW

**Comment by arunoda** [comment]
Thanks.

**Comment by arunoda** [comment]
Actually, I revert this PR.
When it's time to publish the package, I'm getting these errors.

```
error: Conflict: Constraint ecmascript@0.3.0 is not satisfied by ecmascript
0.1.6.
Constraints on package "ecmascript":
* ecmascript@=0.1.6 <- top level
* ecmascript@0.3.0 <- jsx 0.2.4 <- react 0.14.3_1 <- kadira:react-layout
1.5.4
* ecmascript@0.1.6 <- coffeescript 1.0.11 <- cosmos:browserify 0.9.2 <-
kadira:react-layout 1.5.4
* ecmascript@0.1.3 <- caching-compiler 1.0.0 <- coffeescript 1.0.11 <-
cosmos:browserify 0.9.2 <- kadira:react-layout 1.5.4
* ecmascript@0.1.3 <- caching-compiler 1.0.0 <- cosmos:browserify 0.9.2 <-
kadira:react-layout 1.5.4
* ecmascript@0.1.6 <- random 1.0.5 <- caching-compiler 1.0.0 <- coffeescript
1.0.11 <- cosmos:browserify 0.9.2 <- kadira:react-layout 1.5.4
* ecmascript@0.1.6 <- random 1.0.5 <- caching-compiler 1.0.0 <-
cosmos:browserify 0.9.2 <- kadira:react-layout 1.5.4
* ecmascript@0.1.6 <- random 1.0.5 <- local-test:kadira:react-layout 1.5.4
* ecmascript@0.1.6 <- ddp-server 1.2.2 <- ddp 1.2.2 <- mongo 1.1.3 <-
tinytest 1.0.6 <- local-test:kadira:react-layout 1.5.4
* ecmascript@0.1.6 <- ddp-server 1.2.2 <- ddp 1.2.2 <- tinytest 1.0.6 <-
local-test:kadira:react-layout 1.5.4
```

I tried several ways. Can't find a solution.
Seems like Meteor 1.2 has a hard dependency on `ecmascript@=0.1.6`.
That's bad.

Looking for some help. @stubailo any help?

**Comment by stubailo** [comment]
Yes, I believe this new wrapper only works with Meteor 1.3 - I think @benjamn wanted to switch the `jsx` handling to the `ecmascript` package.

**Comment by arunoda** [comment]
Thanks we'll wait then.

**Pull request merged**
