### PR TITLE
Updated dependency on React to 0.14.3

### PR DESCRIPTION
**Pull request by JasperH8g**
There's an open [PR](https://github.com/meteor/react-packages/pull/146) to update React to 0.14.3. This dependency-update is to be ready for when that's merged.

### CODE REVIEW

**Comment by arunoda** [comment]
Awesome. Could you ping me once it's merged and released. I'll publish a new version.

**Comment by JasperH8g** [comment]
Will do :+1:

**Comment by arunoda** [comment]
Great.

**Comment by JasperH8g** [comment]
React has been updated: https://github.com/meteor/react-packages/pull/145

**Comment by arunoda** [comment]
I'll wait a day or two until it's pushed to the atmosphere.

**Comment by JasperH8g** [comment]
Just FYI, the update is published to atmosphere.

**Comment by arunoda** [comment]
Thanks.

**Comment by arunoda** [comment]
Published.

**Comment by JasperH8g** [comment]
Thanks :+1:

**Pull request merged**
